name: ignored-by-path
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  # Core analytics stack
  - numpy
  - pandas
  - geopandas
  - shapely
  - requests
  - scikit-learn
  - python-dotenv
  - ruff
  - black
  - mypy
  - pytest
  - pytest-cov
  - ipykernel
  - pre-commit
